sudo: required
dist: trusty
language: cpp
script: cmake

matrix:
    include:
        # OSX
        - os: osx
          compiler: clang

        - os: linux
          compiler: gcc
          addons: &gcc
            apt:
              packages:
                - util-linux
                - g++-4.9
              sources:
                - ubuntu-toolchain-r-test
                
before_install:
    - curl -O https://distfiles.macports.org/MacPorts/MacPorts-2.5.2.tar.bz2
    - tar xf MacPorts-2.5.2.tar.bz2
    - cd MacPorts-2.5.2/
    - ./configure
    - make
    - sudo make install
    - export PATH=/opt/local/bin:/opt/local/sbin:$PATH
    - sudo port -v selfupdate
    - yes | sudo port install git
    - yes | sudo port install cmake
    - $CXX --version
    - which $CXX
    - $CC --version
    - which $CC
    - which cmake
    - /usr/local/bin/cmake --version
    - git clone --quiet --recurse-submodules https://github.com/boostorg/boost.git -b boost-1.58.0

# Build steps
script:
    - mkdir build
    - cd build
    - /usr/local/bin/cmake .. -DBUILD_WITH_SOURCES_DIR=${TRAVIS_BUILD_DIR}/boost && make -j$(nproc) all && make -j$(nproc) tests
