sudo: required
dist: trusty
language: cpp
script: cmake

matrix:
    include:
        # OSX
        - os: osx
          compiler: clang

        - os: linux
          compiler: gcc
          addons: &gcc
            apt:
              packages:
                - util-linux
                - g++-4.9
              sources:
                - ubuntu-toolchain-r-test
                
before_install:
    - wget https://cmake.org/files/v3.10/cmake-3.10.0-Darwin-x86_64.tar.gz
    - tar xf cmake-3.10.0-Darwin-x86_64.tar.gz
    - export PATH="`pwd`/cmake-3.10.0-Darwin-x86_64/CMake.app/Contents/bin:$PATH"
    - $CXX --version
    - which $CXX
    - $CC --version
    - which $CC
    - which cmake
    - cmake --version
    - git clone --quiet --recurse-submodules https://github.com/boostorg/boost.git -b boost-1.58.0

# Build steps
script:
    - mkdir build
    - cd build
    - `pwd`/cmake-3.10.0-Darwin-x86_64/CMake.app/Contents/bin/cmake .. -DBUILD_WITH_SOURCES_DIR=${TRAVIS_BUILD_DIR}/boost && make -j$(nproc) all && make -j$(nproc) tests
