sudo: required
dist: trusty
language: cpp
script: cmake

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
       wget https://cmake.org/files/v3.10/cmake-3.10.0-Darwin-x86_64.tar.gz &&  tar xf cmake-3.10.0-Darwin-x86_64.tar.gz && export PATH="`pwd`/cmake-3.10.0-Darwin-x86_64/CMake.app/Contents/bin:$PATH"; 
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      sudo apt-get install -y zlib1g-dev libbz2-dev mpich &&
      sudo apt-get install -y python3-dev python3-pip python3-tk python3-lxml python3-six &&
      sudo apt-get install -y libssl-dev &&
      sudo apt-get install -y libicu-dev libc6-dev  &&
      sudo apt-get install -y bsdmainutils build-essential autotools-dev automake autoconf git &&
      wget https://cmake.org/files/v3.11/cmake-3.11.0-Linux-x86_64.sh &&
      sudo sh cmake-3.11.0-Linux-x86_64.sh --prefix=/usr/local --exclude-subdir &&
      export PATH="/usr/local/bin:$PATH";   
    fi
    
    
before_script:
    - $CXX --version
    - which $CXX
    - $CC --version
    - which $CC
    - which cmake
    - cmake --version
    - git clone --recurse-submodules https://github.com/boostorg/boost.git -b boost-1.58.0

# Build steps
script:
    - mkdir build
    - cd build
    - cmake .. -DBUILD_WITH_SOURCES_DIR=${TRAVIS_BUILD_DIR}/boost && make -j$(nproc) all && make -j$(nproc) tests
    
